### ISSUE TITLE
Files are deleted after changing package name.

### ISSUE THREAD

**Issue by softwebtuts** [junedomingo/react-native-rename#114]
### Files are being deleted while changing the package name.

Like if my package name is:
`com.example`

and I want to change it with:
`com.example.app`

Then all the java files are deleted from the main directory.

**Comment by jsancho** [comment]
Experiencing same issue here when running with bundle identifier

`npx react-native-rename "App Name" -b "com.my.app.bundle.name"`

`MainApplication.java` and `MainActivity.java` are deleted instead of having their package name changed.


![image](https://user-images.githubusercontent.com/1547884/98229194-e6395700-1f59-11eb-8b3c-8303e995b1d2.png)

**Comment by yfunk** [comment]
I had the same issue, the workaround i found was to manually create the folder structure in `android/app/src/main/java` and move `MainActivity.java` and `MainApplication.java` there before running the command.

**Comment by vomchik** [comment]
WIP #113

**Comment by davimello28** [comment]
Same here.

**Comment by vomchik** [comment]
Fixed in v2.6.0
