### ISSUE TITLE
Doesn't change ios/* names

### ISSUE THREAD

**Issue by mehranabi** [junedomingo/react-native-rename#43]
Hello,
react-native-rename dosn't change name of files in 'ios' dir, This is a sample:

```
D:\Project\MyProject>react-native-rename "TheName"
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
\android\app\src\main\res\values\strings.xml MODIFIED
\index.js MODIFIED
\package.json MODIFIED
\app.json MODIFIED
\android\settings.gradle MODIFIED
\app.json MODIFIED
The system cannot find the path specified.
The system cannot find the path specified.
\android\app\BUCK MODIFIED
\android\app\build.gradle MODIFIED
\android\app\src\main\AndroidManifest.xml MODIFIED
Done removing previous bundle directory.
Done removing builds.
APP SUCCESSFULLY RENAMED TO "TheName"! 🎉 🎉 🎉
Please make sure to run "watchman watch-del-all" and "npm start --reset-cache" before running the app.
```

System Info:
--- Windows 10 Enterprise
--- React Version : 16.2.0
--- React Native Version : 0.52.2

**Comment by daddevs** [comment]
I had the same exact issue when I just tried running the rename tool as well. Same results.

System Info:
--- Windows 10 Home
--- React Native Version: 0.51
created using react-native init

**Comment by ajcrites** [comment]
This issue may be specific to Windows.

**Comment by nkovacic** [comment]
This issue is present on macOs and windows 10. It seems that it searching for files with new name instead of the old name to rename.

**Comment by mayuroks** [comment]
Facing the same issue.
@junedomingo need help!

**Comment by rahamin1** [comment]
Any solution anyone? I am getting this on Windows 10

**Comment by Pushplaybang** [comment]
same errors on OSX

**Comment by OleksiiLyhun** [comment]
have same errors on OSX

**Comment by flaviocolonna** [comment]
Hi guys!
The problem seems to be related with the name contained in the _android/app/src/main/res/values/strings.xml_ file.
The developer is using that _app_name_ value to iterate over the files under the _ios_ folder.
I suggest to use the one in the _app.json_ defined as _name_.
So, if you want a quick fix, change the _app_name_ with the one used by _ios_.

**Comment by ermankuruoglu** [comment]
Thanks @flaviocolonna this resolved my issue.

**Comment by tejas77** [comment]
@junedomingo 
This issue is on this where you have added **2>/dev/null**, which doesn't exist on Windows 10, reference: [Windows equivalent of “> /dev/null &”](https://stackoverflow.com/a/53897509/8720323)

https://github.com/junedomingo/react-native-rename/blob/d27289fa74c55991efe2b923ab29972e4abac140/src/index.js#L122

What I did was gone to the global npm package where I installed the package: react-native-rename and changed the line. Developers, if you wish to also make it work on Windows. @mehranabi 

Go to 
`C:\Users\<username>\AppData\Roaming\npm\node\node_modules\react-native-rename\lib`
open `index.js line:160`:
Change `2>/dev/null` to `2>NUL`

I tested and the code runs properly on macOS but didn't on Windows.

**Comment by emreakbaba** [comment]
This problem seem caused by the Bundle Name and the Project Folder Name mismatch. A quick solution which i used is:

`react-native-rename "DesiredName"`   this will output invalid path error. then:
`react-native-rename "CurrentName"`   this will solve the issue about the path to check for. then finally:
`react-native-rename "DesiredName"`
