### ISSUE TITLE
Android package name case sensitiveness.

### ISSUE THREAD

**Issue by oidoug** [junedomingo/react-native-rename#50]
Hi, thanks for the great package, being using it a lot.

But I got into a pesky problem. On Android, some of my app package names already on play store have upper case letters. rn-rename (on line 81 and in other parts) set the bundleid toLowerCase(). Google doesn't allow the package name to change.

Is there a way I'm missing to keep the case sensitiveness on renaming the Android project?
If not, I'm considering developing this feature in rn-rename myself. In that case, what would be the right way to do it?

Thanks in advance.

**Comment by ajcrites** [comment]
It seems like some people may want an option to specify the Android package name for the APK and have this different than the source package name (which I believe has to be lowercase).

**Comment by junedomingo** [comment]
Closing, check v3

**Comment by 01madbouly** [comment]
I faced the same issue,
DataBinding does not work with my package name because it has upper letters. 
My App is already published on google play. 
So
I changed package name upper letters to small letters in all project and in namespace 
But
 I left only applicationId with old package name (with upper litters)

And it work fine, and I uploaded my app to google play successfully.

**Comment by junedomingo** [comment]
@01madbouly what version of rnr are you on?
